version: '3.7'

services:
  photos:
    image: presw/closely_photos
    command: npm start
    restart: always
    depends_on:
      - 'database'
    ports: 
      - '3003:3003'

  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=closely
    ports:
      - '3306:3306'
